sudo: required
services:
- docker
language: bash
script:
# compile qemu from source and build image
- ./build.sh
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker tag sfalexrog/qemu-register sfalexrog/qemu-register:v4.1.0
    docker push sfalexrog/qemu-register:v4.1.0
    docker push sfalexrog/qemu-register:latest
  fi
